name: GitHub Actions Demo

on: [pull_request_target, issues, push]

jobs:
  greet:
    runs-on: self-hosted
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello GitHub Actioins Demo"
      
