name: Hello Precision

on:
  push:
   branches:
    - 'main'
  pull_request:
   branches:
    - 'main'

jobs:
  hello:
   runs-on: self-hosted
   steps:
    - name: Bash
      shell: bash
      run: ls -la